version: "3.7"

services:
  person-service:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_server_arch}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: ["-Xmx${_Values_resources_requests_memory}"]

#    we cannot active the healthcheck because base native images does not have curl
#    healthcheck:
#      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
#      interval: 10s
#      timeout: 10s
#      retries: 5
    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      - TZ=Europe/Berlin
      - quarkus.http.port=${_Values_service_port}
      - quarkus.http.io-threads=20
      #persistence
      - quarkus.datasource.db-kind=postgresql
      - quarkus.datasource.jdbc.url=jdbc:postgresql://${_Values_root_name}-postgres:5432/persondb
      - quarkus.datasource.username=person-service
      - quarkus.datasource.password=person-service
      - quarkus.datasource.jdbc.max-size=10
      #adapter
      - adapter.calleeservice.url=http://host.docker.internal:50900
      #logging
      - quarkus.log.level=INFO
      - quarkus.log.category."org.goafabric".level=INFO
      - quarkus.log.category."org.flywaydb.core".level=INFO
      - quarkus.log.category."org.hibernate".level=INFO

  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:13.2
    restart: 'no'
    ports:
      - 50810:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=person-service
      - POSTGRES_PASSWORD=person-service
      - POSTGRES_DB=persondb
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ../config/postgres/initdb/00_pg_statements.sql:/docker-entrypoint-initdb.d/00_pg_statements.sql
    networks:
      - ${_Values_root_name}-net

volumes:
    tmp:
    applogs:
    pgdata:

networks:
  person-service-net:
    driver: bridge