FROM ghcr.io/graalvm/graalvm-ce:ol7-java11-22.2.0 AS build
RUN gu install native-image
WORKDIR /project
VOLUME ["/project"]
ENTRYPOINT ["native-image"]

#https://dev.to/nevernull/building-a-native-java-application-for-arm64-with-quarkus-2n9m
#docker build -f Dockerfile.build.aarch64 -t goafabric/quarkus-build-aarch64:ol7-java11-22.2.0 .
